### ISSUE TITLE
Replace Docker stack deploy link

### ISSUE THREAD

**Issue by dominikbraun** [Evalle/DCA#15]
The hyperlink "Convert an application deployment into a stack file using a YAML compose file with "docker stack deploy" in domain 1 currently refers to the [corresponding command reference](https://docs.docker.com/engine/reference/commandline/stack_deploy/). IMO, the docs would be a better fit: https://docs.docker.com/engine/swarm/stack-deploy/

It is more comprehensive and the other links refer to the docs as well.

**Comment by Evalle** [comment]
Done, thank you!
