### ISSUE TITLE
Revised DCA prep guide

### ISSUE THREAD

**Issue by vpatiltech** [Evalle/DCA#16]
Official DCA prep guide is recently updated(May 2020) and contains some new topics. New topics also covers references to Kubernetes. Is it possible to update this study guide to include new entries in syllabus?

**Comment by tomtrapp** [comment]
+1

**Comment by Evalle** [comment]
Hey guys, thanks for the messages. I'm gonna take a look.

**Comment by vpatiltech** [comment]
Thanks for acknoledgment. I am open for contrubution/help.

**Comment by xyshell** [comment]
Hi guys, Currently I'm preparing for DCA, and noticed that there is some change to the study guide v1.3. I've finished the domain 1 so far and will also update the rest as my preparation moves forward. However, the updating speed is subject to my study pace.

By the way, I'm also writing some personal comments below each question. those are available on my [website](https://xyshell.github.io/2020/06/11/DCA-note/). I'm also willing to incorporate them to this repo if you guys want.

**Comment by Evalle** [comment]
Hi @xyshell feel free to create more PRs!
