### ISSUE TITLE
Domain 1: Apply node labels to demonstrate placement of tasks

### ISSUE THREAD

**Issue by mohclips** [Evalle/DCA#30]
https://success.mirantis.com/article/using-contraints-and-labels-to-control-the-placement-of-containers

This link is no longer available at Mirantis 😞 

try this as a replacement:  https://docs.docker.com/engine/swarm/services/#control-service-placement

**Comment by Evalle** [comment]
HI @mohclips, thanks for the heads-up let me check it out.
