### ISSUE TITLE
Domain 4: Describe and demonstrate how to troubleshoot container and engine logs to resolve connectivity issues between containers

### ISSUE THREAD

**Issue by konradzagozda** [Evalle/DCA#36]
link redirects to main page: https://training.mirantis.com/

possible replacements:
- https://docs.docker.com/engine/reference/commandline/logs/
- https://docs.docker.com/config/daemon/logs/

**Comment by Evalle** [comment]
fixed via: https://github.com/Evalle/DCA/commit/db1def002f4ba82ca96e3ffb7729902b3ca5b529
