### ISSUE TITLE
Describe process to use external certificates with UCP and DTR 

### ISSUE THREAD

**Issue by dipanjanmukherjee83** [Evalle/DCA#9]
For UCP external certificates we can use the below links. Please check it.
from cli : https://success.docker.com/article/how-do-i-provide-an-externally-generated-security-certificate-during-the-ucp-command-line-installation 

from gui : https://docs.docker.com/ee/ucp/admin/configure/use-your-own-tls-certificates/

print public certs : https://docs.docker.com/reference/ucp/3.0/cli/dump-certs/

**Comment by Evalle** [comment]
Hey @dipanjanmukherjee83 thanks a lot for the links, I've added them to the repo.
